export const USER_REGISTER="USER_REGISTER"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED"


export const USER_LOGIN="USER_lOGIN"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"


export const GET_PROFILE="GET_PROFILE"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED"

export const LOGOUT = "LOGOUT"

export const GET_SHOES="GET_SHOES"
export const GET_SHOES_SUCCESS = "GET_SHOES_SUCCESS"
export const GET_SHOES_FAILED = "GET_SHOES_FAILED"

export const GET_SHOES_BYID="GET_SHOES_BYID"
export const GET_SHOES_BYTYPE="GET_SHOES_BYTYPE"


export const PANIER_REGISTER="PANIER_REGISTER"
export const PANIER_REGISTER_SUCCESS = "PANIER_REGISTER_SUCCESS"
export const PANIER_REGISTER_FAILED = "PANIER_REGISTER_FAILED"

export const GET_PANIER="GET_PANIER"
export const GET_PANIER_SUCCESS = "GET_PANIER_SUCCESS"
export const GET_PANIER_FAILED = "GET_PANIER_FAILED"


